### ISSUE TITLE
Add a gradle build to test suite

### ISSUE THREAD

**Issue by sasbury** [nats-io/spring-nats#6]
Gradle is stricter on the XML so this would insure that the main pom files are ok with gradle

**Comment by YunaBraska** [comment]
Sorry for the late answer. Maybe I need to get more active on this repository. In short, I don't think that this request make sense. Maybe you can provide an example of your issue. Maven and Gradle should produce the same artifacts. Just the style is differen.

Maven is often considered more robust than Gradle for several reasons. First, Maven's convention-over-configuration approach ensures a standardized and predictable build process. This reduces the likelihood of errors due to inconsistent configurations across different projects. Maven’s dependency management is also more straightforward and less prone to conflicts, as it uses a fixed, declarative format for defining dependencies.

In contrast, Gradle's flexibility, while powerful, can lead to complexity and inconsistency, particularly in larger projects or teams. Gradle scripts, being written in Groovy or Kotlin, offer a lot of power and customization, but this can also result in scripts that are hard to read and maintain, especially for those not familiar with these languages.

Furthermore, Maven's plugin ecosystem is mature and stable. While Gradle has a growing number of plugins, Maven's long-standing presence in the industry means that its plugins are often more tested and reliable. Maven's stability and predictability make it a preferred choice in environments where these attributes are prioritized over the flexibility and performance optimizations offered by Gradle.
